sudo: false
language: ruby
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.13.7
addons:
  code_climate:
    repo_token: b41ea4bb00784bf99e8e5f1d8092165cb7f3077f45e17813376751e141e98bba
after_success:
  - bundle exec codeclimate-test-reporter